//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace thuc_pham_sach_hd.EF
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class ChiTietDonHang
    {
        
        public int Id_Order { get; set; }
        public int Id_SP { get; set; }
        [Display(Name ="Giá Sản Phẩm")]
        public Nullable<double> GiaSP { get; set; }
        [Display(Name ="Số Lượng")]
        public Nullable<int> SoLuong { get; set; }
        [Display(Name ="Tổng Tiền")]
        public Nullable<double> TongTien { get; set; }
        [Display(Name ="Trạng Thái")]
        public Nullable<bool> Status { get; set; }
        [Display(Name ="Ngày lập")]
        public Nullable<System.DateTime> NgayTao { get; set; }
        
        [Display(Name ="Đơn Hàng")]
        public virtual DonHang DonHang { get; set; }
        [Display(Name ="Sản phẩm")]
        public virtual SanPham SanPham { get; set; }
    }
}
