//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace thuc_pham_sach_hd.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class DonHang
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DonHang()
        {
            this.ChiTietDonHang = new HashSet<ChiTietDonHang>();
        }
    
        public int Id_Order { get; set; }
        public Nullable<int> Id_KH { get; set; }
        public string Ten_KHDat { get; set; }
        public string SDT_KHDat { get; set; }
        public string Email_KHDat { get; set; }
        public string DiaChi_KHDat { get; set; }
        public string Ten_KHNhan { get; set; }
        public string SDT_KHNhan { get; set; }
        public string DiaChi_KHNhan { get; set; }
        public string Email_KHNhan { get; set; }
        public string YeuCau { get; set; }
        public Nullable<double> TongTien { get; set; }
        public Nullable<System.DateTime> NgayDatHang { get; set; }
        public Nullable<bool> TrangThai { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChiTietDonHang> ChiTietDonHang { get; set; }
        public virtual KhachHang KhachHang { get; set; }
    }
}
