//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace thuc_pham_sach_hd.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class QuyenHan
    {
        public int Id_Quyen { get; set; }
        public string TenQuyen { get; set; }
        public string MaNghiepVu { get; set; }
        public string MoTa { get; set; }
    }
}
