//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace thuc_pham_sach_hd.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Slide
    {
        public int Id_Slide { get; set; }
        public string TieuDe { get; set; }
        public string Mota { get; set; }
        public string HinhAnh { get; set; }
        public Nullable<int> ViTri { get; set; }
        public Nullable<bool> TrangThai { get; set; }
    }
}
